# Generated by Django 5.2.2 on 2025-11-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_mode',
            field=models.CharField(choices=[('ONSITE', 'On-Site'), ('REMOTE', 'Remote'), ('HYBRID', 'Hybrid')], default='ONSITE', max_length=20),
        ),
    ]
