# Generated by Django 5.2.2 on 2025-11-08 07:17

import apps.resignation.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResignationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resignation_date', models.DateField()),
                ('last_working_day', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('other_reason', models.CharField(blank=True, max_length=512, null=True)),
                ('signature_data', models.TextField(blank=True, null=True)),
                ('resignation_letter', models.FileField(blank=True, null=True, upload_to=apps.resignation.models.resignation_letter_upload_path)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resignations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resignation_request',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
