# Generated by Django 5.2.8 on 2025-11-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='type',
            field=models.CharField(choices=[('NATIONAL', 'National Holiday'), ('RELIGIOUS', 'Religious Holiday'), ('COMPANY', 'Company Holiday'), ('OPTIONAL', 'Optional Holiday')], default='COMPANY', max_length=10),
        ),
    ]
